"""empty message

Revision ID: 6d7ad0cb8c2a
Revises: 
Create Date: 2020-06-15 05:55:31.371280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d7ad0cb8c2a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('message', 'message',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'message',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    op.alter_column('message', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###
